apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - public-ingress-websocket.yaml
  - public-ingress-http.yaml
  - ../../base
namespace: prod

commonLabels:
  environment: prod

images:
  - name: nginx:stable-alpine
    newName: andresupmh/homepage-api
    newTag: prod-359634e

patches:
- target:
    kind: Deployment
    name: homepage-api
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1

# Tailscale-only — remove base nginx Ingress to avoid host conflicts
- target:
    kind: Ingress
    name: homepage-api
  patch: |-
    $patch: delete
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: homepage-api

# Generated secrets by Kaanbal Engine
secretGenerator:
  - name: homepage-api-secrets
    literals:
      - SECRET_KEY=zJdNz0ioqj5AYIED3XNUIEzf
      - MONGODB_URI=
      - HOMEPAGE_DB_HOST=homepage-db.prod.svc.cluster.local
      - HOMEPAGE_DB_PORT=27017
      - HOMEPAGE_DB_DATABASE=homepage_api
      - HOMEPAGE_DB_USER=proadmin
      - HOMEPAGE_DB_PASSWORD=Hvh0DtFdd5WkEN51oCP9sNuz
      - HOMEPAGE_DB_URI=mongodb://proadmin:Hvh0DtFdd5WkEN51oCP9sNuz@homepage-db.prod.svc.cluster.local:27017/homepage_api?authSource=admin
