apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: prod

commonLabels:
  environment: prod

images:
  - name: nginx:stable-alpine
    newName: andresupmh/constructora
    newTag: prod-5b12557

patches:
- target:
    kind: Deployment
    name: constructora
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1

- target:
    kind: Ingress
    name: constructora
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: constructora.futurefarms.mx
    - op: replace
      path: /spec/tls/0/hosts/0
      value: constructora.futurefarms.mx
    - op: replace
      path: /spec/tls/0/secretName
      value: tls-constructora

# Generated secrets by Kaanbal Engine
secretGenerator:
  - name: constructora-secrets
    literals:
      - APP_SECRET=LLueOqhSpDJBn7BWe5JSLC7X
