apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: dev

commonLabels:
  environment: dev

images:
  - name: nginx:stable-alpine
    newName: andresupmh/constructora
    newTag: dev-e4b4fe3

patches:
- target:
    kind: Deployment
    name: constructora
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1

- target:
    kind: Ingress
    name: constructora
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev-constructora.futurefarms.mx
    - op: replace
      path: /spec/tls/0/hosts/0
      value: dev-constructora.futurefarms.mx
    - op: replace
      path: /spec/tls/0/secretName
      value: tls-dev-constructora

# Generated secrets by Kaanbal Engine
secretGenerator:
  - name: constructora-secrets
    literals:
      - APP_SECRET=stSVRa3GAsEAHLj9q5yjYWwa
