apiVersion: v1
kind: Service
metadata:
  name: homepage-api
  namespace: prod
  labels:
    app: homepage-api
spec:
  selector:
    app: homepage-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
