apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
# Updated by CI/CD pipeline on each deploy
images:
  - name: andresupmh/constructora
    newTag: latest
