apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - enterprise.futurefarms.mx
      secretName: enterprise-tls
  rules:
    - host: enterprise.futurefarms.mx
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enterprise
                port:
                  number: 80
