apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: tailscale

# En dev, usamos la imagen stable
images:
  - name: tailscale/k8s-operator
    newTag: stable
