apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- tailscale-svc.yaml
namespace: dev

commonLabels:
  environment: dev

patches:
- target:
    kind: Deployment
    name: fago-bd-postgres
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1


# Generated secrets by Kaanbal Engine
secretGenerator:
  - name: fago-bd-postgres-secrets
    literals:
      - POSTGRES_USER=devadmin
      - POSTGRES_PASSWORD=CHANGE_ME
      - POSTGRES_DB=fago_bd_postgres
